export const helperCountries = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "American Samoa",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antarctica",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Aruba",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas (the)",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bermuda",
  "Bhutan",
  "Bolivia (Plurinational State of)",
  "Bonaire, Sint Eustatius and Saba",
  "Bosnia and Herzegovina",
  "Botswana",
  "Bouvet Island",
  "Brazil",
  "British Indian Ocean Territory (the)",
  "Brunei Darussalam",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Cayman Islands (the)",
  "Central African Republic (the)",
  "Chad",
  "Chile",
  "China",
  "Christmas Island",
  "Cocos (Keeling) Islands (the)",
  "Colombia",
  "Comoros (the)",
  "Congo (the Democratic Republic of the)",
  "Congo (the)",
  "Cook Islands (the)",
  "Costa Rica",
  "Croatia",
  "Cuba",
  "Curaçao",
  "Cyprus",
  "Czechia",
  "Côte d'Ivoire",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic (the)",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Falkland Islands (the) [Malvinas]",
  "Faroe Islands (the)",
  "Fiji",
  "Finland",
  "France",
  "French Guiana",
  "French Polynesia",
  "French Southern Territories (the)",
  "Gabon",
  "Gambia (the)",
  "Georgia",
  "Germany",
  "Ghana",
  "Gibraltar",
  "Greece",
  "Greenland",
  "Grenada",
  "Guadeloupe",
  "Guam",
  "Guatemala",
  "Guernsey",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Heard Island and McDonald Islands",
  "Holy See (the)",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran (Islamic Republic of)",
  "Iraq",
  "Ireland",
  "Isle of Man",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jersey",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Korea (the Democratic People's Republic of)",
  "Korea (the Republic of)",
  "Kuwait",
  "Kyrgyzstan",
  "Lao People's Democratic Republic (the)",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Macao",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands (the)",
  "Martinique",
  "Mauritania",
  "Mauritius",
  "Mayotte",
  "Mexico",
  "Micronesia (Federated States of)",
  "Moldova (the Republic of)",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Montserrat",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands (the)",
  "New Caledonia",
  "New Zealand",
  "Nicaragua",
  "Niger (the)",
  "Nigeria",
  "Niue",
  "Norfolk Island",
  "Northern Mariana Islands (the)",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine, State of",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines (the)",
  "Pitcairn",
  "Poland",
  "Portugal",
  "Puerto Rico",
  "Qatar",
  "Republic of North Macedonia",
  "Romania",
  "Russian Federation (the)",
  "Rwanda",
  "Réunion",
  "Saint Barthélemy",
  "Saint Helena, Ascension and Tristan da Cunha",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Martin (French part)",
  "Saint Pierre and Miquelon",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Sint Maarten (Dutch part)",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Georgia and the South Sandwich Islands",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan (the)",
  "Suriname",
  "Svalbard and Jan Mayen",
  "Sweden",
  "Switzerland",
  "Syrian Arab Republic",
  "Taiwan",
  "Tajikistan",
  "Tanzania, United Republic of",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tokelau",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Turks and Caicos Islands (the)",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates (the)",
  "United Kingdom of Great Britain and Northern Ireland (the)",
  "United States Minor Outlying Islands (the)",
  "United States of America (the)",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela (Bolivarian Republic of)",
  "Viet Nam",
  "Virgin Islands (British)",
  "Virgin Islands (U.S.)",
  "Wallis and Futuna",
  "Western Sahara",
  "Yemen",
  "Zambia",
  "Zimbabwe",
  "Åland Islands",
];

export const continents = [
  {
    continent: "Africa",
    codes: [
      "AO",
      "BF",
      "BI",
      "BJ",
      "BW",
      "CD",
      "CF",
      "CG",
      "CI",
      "CM",
      "CV",
      "DJ",
      "DZ",
      "EG",
      "EH",
      "ER",
      "ET",
      "GA",
      "GH",
      "GM",
      "GN",
      "GQ",
      "GW",
      "KE",
      "KM",
      "LR",
      "LS",
      "LY",
      "MA",
      "MG",
      "ML",
      "MR",
      "MU",
      "MW",
      "MZ",
      "NA",
      "NE",
      "NG",
      "RE",
      "RW",
      "SC",
      "SD",
      "SH",
      "SL",
      "SN",
      "SO",
      "SS",
      "ST",
      "SZ",
      "TD",
      "TG",
      "TN",
      "TZ",
      "UG",
      "YT",
      "ZA",
      "ZM",
      "ZW",
    ],
    countries: [
      "Angola",
      "Burkina Faso",
      "Burundi",
      "Benin",
      "Botswana",
      "Democratic Republic of Congo",
      "Central African Republic",
      "Congo",
      "Cote D'Ivoire",
      "Cameroon",
      "Cape Verde",
      "Djibouti",
      "Algeria",
      "Egypt",
      "Western Sahara",
      "Eritrea",
      "Ethiopia",
      "Gabon",
      "Ghana",
      "Gambia",
      "Guinea",
      "Equatorial Guinea",
      "Guinea-bissau",
      "Kenya",
      "Comoros",
      "Liberia",
      "Lesotho",
      "Libyan Arab Jamahiriya",
      "Morocco",
      "Madagascar",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Malawi",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Reunion",
      "Rwanda",
      "Seychelles",
      "Sudan",
      "St. Helena",
      "Sierra Leone",
      "Senegal",
      "Somalia",
      "",
      "Sao Tome and Principe",
      "Swaziland",
      "Chad",
      "Togo",
      "Tunisia",
      "Tanzania",
      "Uganda",
      "Mayotte",
      "South Africa",
      "Zambia",
      "Zimbabwe",
    ],
  },
  {
    continent: "Middle East/Others",
    codes: [
      "AE",
      "AF",
      "AM",
      "AZ",
      "BD",
      "BH",
      "BN",
      "BT",
      "CC",
      "CN",
      "CX",
      "CY",
      "GE",
      "HK",
      "ID",
      "IL",
      "IN",
      "IO",
      "IQ",
      "IR",
      "JO",
      "JP",
      "KG",
      "KH",
      "KP",
      "KR",
      "KW",
      "KZ",
      "LA",
      "LB",
      "LK",
      "MM",
      "MN",
      "MO",
      "MV",
      "MY",
      "NP",
      "OM",
      "PH",
      "PK",
      "PS",
      "QA",
      "RU",
      "SA",
      "SG",
      "SY",
      "TH",
      "TJ",
      "TL",
      "TM",
      "TR",
      "TW",
      "UZ",
      "VN",
      "XD",
      "XE",
      "XS",
      "YE",
      "AS",
      "AU",
      "CK",
      "FJ",
      "FM",
      "GU",
      "KI",
      "MH",
      "MP",
      "NC",
      "NF",
      "NR",
      "NU",
      "NZ",
      "PF",
      "PG",
      "PN",
      "PW",
      "SB",
      "TK",
      "TO",
      "TV",
      "UM",
      "VU",
      "WF",
      "WS",
      "XX",
      "AQ",
      "BV",
      "GS",
      "HM",
      "TF",
    ],
    countries: [
      "Antarctica",
      "Bouvet Island",
      "South Georgia And The South Sandwich Islands",
      "Heard and Mc Donald Islands",
      "French Southern Territories",
      "United Arab Emirates",
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bangladesh",
      "Bahrain",
      "Brunei Darussalam",
      "Bhutan",
      "Cocos (Keeling) Islands",
      "China",
      "Christmas Island",
      "Cyprus",
      "Georgia",
      "Hong Kong",
      "Indonesia",
      "Israel",
      "India",
      "British Indian Ocean Territory",
      "Iraq",
      "Iran (Islamic Republic of)",
      "Jordan",
      "Japan",
      "Kyrgyzstan",
      "Cambodia",
      "North Korea",
      "Korea, Republic of",
      "Kuwait",
      "Kazakhstan",
      "Lao People's Democratic Republic",
      "Lebanon",
      "Sri Lanka",
      "Myanmar",
      "Mongolia",
      "Macau",
      "Maldives",
      "Malaysia",
      "Nepal",
      "Oman",
      "Philippines",
      "Pakistan",
      "Qatar",
      "Russian Federation",
      "Saudi Arabia",
      "Singapore",
      "Syrian Arab Republic",
      "Thailand",
      "Tajikistan",
      "Turkmenistan",
      "Turkey",
      "Taiwan",
      "Uzbekistan",
      "Viet Nam",
      "Yemen",
      "American Samoa",
      "Australia",
      "Cook Islands",
      "Fiji",
      "Micronesia, Federated States of",
      "Guam",
      "Kiribati",
      "Marshall Islands",
      "Northern Mariana Islands",
      "New Caledonia",
      "Norfolk Island",
      "Nauru",
      "Niue",
      "New Zealand",
      "French Polynesia",
      "Papua New Guinea",
      "Pitcairn",
      "Palau",
      "Solomon Islands",
      "Tokelau",
      "Tonga",
      "Tuvalu",
      "United States Minor Outlying Islands",
      "Vanuatu",
      "Wallis and Futuna Islands",
      "Samoa",
    ],
  },
  {
    continent: "Europe",
    codes: [
      "GE",
      "GG",
      "GR",
      "HR",
      "HU",
      "IE",
      "IM",
      "IT",
      "JE",
      "LI",
      "LT",
      "LU",
      "LV",
      "MC",
      "MD",
      "ME",
      "MT",
      "NL",
      "NO",
      "PL",
      "PT",
      "RO",
      "RS",
      "SE",
      "SI",
      "SJ",
      "SK",
      "SM",
      "TR",
      "UA",
      "VA",
      "XK",
      "AD",
      "AL",
      "AM",
      "AT",
      "AX",
      "AZ",
      "BA",
      "BE",
      "BG",
      "BY",
      "CH",
      "CY",
      "CZ",
      "DE",
      "DK",
      "EE",
      "ES",
      "FI",
      "FO",
      "FR",
      "GB",
    ],
    countries: [
      "UK",
      "Andorra",
      "Albania",
      "Armenia",
      "Austria",
      "Azerbaijan",
      "Bosnia and Herzegovina",
      "Belgium",
      "Bulgaria",
      "Belarus",
      "Switzerland",
      "Cyprus",
      "Czech Republic",
      "Germany",
      "Denmark",
      "Estonia",
      "Spain",
      "Finland",
      "Faroe Islands",
      "France",
      "United Kingdom",
      "Georgia",
      "Gibraltar",
      "Greece",
      "Croatia",
      "Hungary",
      "Ireland",
      "Iceland",
      "Italy",
      "Kazakhstan",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Latvia",
      "Monaco",
      "Moldova, Republic of",
      "Macedonia",
      "Malta",
      "Netherlands",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russian Federation",
      "Sweden",
      "Slovenia",
      "Svalbard and Jan Mayen Islands",
      "Slovak Republic",
      "San Marino",
      "Turkey",
      "Ukraine",
      "Vatican City State (Holy See)",
    ],
  },

  {
    continent: "America",
    codes: [
      "AG",
      "AI",
      "AN",
      "AW",
      "BB",
      "BL",
      "BM",
      "BQ",
      "BS",
      "BZ",
      "CA",
      "CR",
      "CU",
      "CW",
      "DM",
      "DO",
      "GD",
      "GL",
      "GP",
      "GT",
      "HN",
      "HT",
      "JM",
      "KN",
      "KY",
      "LC",
      "MF",
      "MQ",
      "MS",
      "MX",
      "NI",
      "PA",
      "PM",
      "PR",
      "SV",
      "SX",
      "TC",
      "TT",
      "UM",
      "US",
      "VC",
      "VG",
      "VI",
      "AR",
      "BO",
      "BR",
      "CL",
      "CO",
      "EC",
      "FK",
      "GF",
      "GY",
      "PE",
      "PY",
      "SR",
      "UY",
      "VE",
      "US",
      "USA",
    ],
    countries: [
      "Antigua and Barbuda",
      "Anguilla",
      "Netherlands Antilles",
      "Aruba",
      "Barbados",
      "Bermuda",
      "Bahamas",
      "Belize",
      "Canada",
      "Costa Rica",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "Grenada",
      "Greenland",
      "Guadeloupe",
      "Guatemala",
      "Honduras",
      "Haiti",
      "Jamaica",
      "Saint Kitts and Nevis",
      "Cayman Islands",
      "Saint Lucia",
      "Martinique",
      "Montserrat",
      "Mexico",
      "Nicaragua",
      "Panama",
      "St. Pierre and Miquelon",
      "Puerto Rico",
      "El Salvador",
      "Turks and Caicos Islands",
      "Trinidad and Tobago",
      "United States Minor Outlying Islands",
      "United States",
      "Saint Vincent and the Grenadines",
      "Virgin Islands (British)",
      "Virgin Islands (U.S.)",
      "Argentina",
      "Bolivia",
      "Brazil",
      "Chile",
      "Colombia",
      "Ecuador",
      "Falkland Islands (Malvinas)",
      "French Guiana",
      "Guyana",
      "Peru",
      "Paraguay",
      "Suriname",
      "Uruguay",
      "Venezuela",
    ],
  },
];
